// ============================================================
// DATA STORE — ElectroTech Egyptian Appliances Store
// Frontend Demonstration Data with 18 Real Products
// ============================================================

const CATEGORIES_DATA = [
  { id: 'all', name: 'جميع الأجهزة', count: 18, image: 'assets/images/products/fridge-01.jpg' },
  { id: 'refrigerators', name: 'ثلاجات وديب فريزر', count: 3, image: 'assets/images/products/fridge-01.jpg' },
  { id: 'washing-machines', name: 'غسالات ومجففات', count: 3, image: 'assets/images/products/washer-01.jpg' },
  { id: 'tvs', name: 'شاشات وتلفزيونات', count: 2, image: 'assets/images/products/tv-02.jpg' },
  { id: 'air-conditioners', name: 'تكييفات هواء', count: 2, image: 'assets/images/products/ac-01.jpg' },
  { id: 'microwaves', name: 'ميكروويف وشوايات', count: 2, image: 'assets/images/products/microwave-01.jpg' },
  { id: 'cookers', name: 'بوتاجازات وأفران', count: 2, image: 'assets/images/products/cooker-01.jpg' },
  { id: 'dishwashers', name: 'غسالات أطباق', count: 1, image: 'assets/images/products/dishwasher-01.jpg' },
  { id: 'small-appliances', name: 'أجهزة منزلية صغيرة', count: 3, image: 'assets/images/products/small-01.jpg' }
];

const PRODUCTS_DATA = [
  {
    id: 1,
    name: "ثلاجة سامسونج نوفروست ديجيتال 4 أبواب RF60 520 لتر",
    brand: "Samsung",
    category: "refrigerators",
    categoryName: "ثلاجات وديب فريزر",
    price: 48999,
    oldPrice: 56500,
    discount: 13,
    image: "assets/images/products/fridge-01.jpg",
    badge: "الأكثر مبيعاً",
    rating: 4.9,
    reviewCount: 142,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: true,
    isDeal: true,
    dealEnds: "2026-10-15T23:59:59"
  },
  {
    id: 2,
    name: "ثلاجة باناسونيك نوفروست سعة 420 لتر انفرتر ستانلس",
    brand: "Panasonic",
    category: "refrigerators",
    categoryName: "ثلاجات وديب فريزر",
    price: 34500,
    oldPrice: 38900,
    discount: 11,
    image: "assets/images/products/fridge-02.jpg",
    badge: "توفير الطاقة",
    rating: 4.7,
    reviewCount: 88,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: true,
    isDeal: false
  },
  {
    id: 3,
    name: "ثلاجة ليبهر ألماني كومفورت ديجيتال 480 لتر مضادة للبكتيريا",
    brand: "Liebherr",
    category: "refrigerators",
    categoryName: "ثلاجات وديب فريزر",
    price: 52000,
    oldPrice: 59000,
    discount: 12,
    image: "assets/images/products/fridge-03.jpg",
    badge: "صناعة ألمانية",
    rating: 4.8,
    reviewCount: 65,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: true,
    isDeal: false
  },
  {
    id: 4,
    name: "غسالة باناسونيك أوتوماتيك تحميل أمامي 9 كجم بخار ذكي",
    brand: "Panasonic",
    category: "washing-machines",
    categoryName: "غسالات ومجففات",
    price: 26900,
    oldPrice: 31000,
    discount: 13,
    image: "assets/images/products/washer-01.jpg",
    badge: "تنظيف بالبخار",
    rating: 4.8,
    reviewCount: 119,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: true,
    isDeal: true,
    dealEnds: "2026-10-12T23:59:59"
  },
  {
    id: 5,
    name: "غسالة بيكو فول أوتوماتيك 8 كجم برو سمارت انفرتر 1200 لفة",
    brand: "Beko",
    category: "washing-machines",
    categoryName: "غسالات ومجففات",
    price: 21500,
    oldPrice: 24900,
    discount: 14,
    image: "assets/images/products/washer-02.jpg",
    badge: "ضمان 10 سنوات",
    rating: 4.6,
    reviewCount: 94,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: true,
    isDeal: false
  },
  {
    id: 6,
    name: "غسالة فاجور إيكو سمارت تحميل أمامي 7 كجم برامج متعددة",
    brand: "Fagor",
    category: "washing-machines",
    categoryName: "غسالات ومجففات",
    price: 18900,
    oldPrice: 21500,
    discount: 12,
    image: "assets/images/products/washer-03.jpg",
    badge: "اقتصادي",
    rating: 4.5,
    reviewCount: 52,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: false,
    isDeal: false
  },
  {
    id: 7,
    name: "شاشة سامسونج سمارت 55 بوصة Crystal UHD 4K رسيفر داخلي",
    brand: "Samsung",
    category: "tvs",
    categoryName: "شاشات وتلفزيونات",
    price: 23999,
    oldPrice: 27999,
    discount: 14,
    image: "assets/images/products/tv-01.jpg",
    badge: "خصم حصري",
    rating: 4.9,
    reviewCount: 230,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: true,
    isDeal: true,
    dealEnds: "2026-10-10T23:59:59"
  },
  {
    id: 8,
    name: "شاشة إل جي OLED evo مقاس 55 بوصة بدقة 4K معالج سينمائي AI",
    brand: "LG",
    category: "tvs",
    categoryName: "شاشات وتلفزيونات",
    price: 49999,
    oldPrice: 58000,
    discount: 14,
    image: "assets/images/products/tv-02.jpg",
    badge: "سينما منزلية",
    rating: 5.0,
    reviewCount: 175,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: true,
    isDeal: false
  },
  {
    id: 9,
    name: "تكييف باناسونيك سبليت انفرتر 1.5 حصان بارد ساخن فائق الهدوء",
    brand: "Panasonic",
    category: "air-conditioners",
    categoryName: "تكييفات هواء",
    price: 28400,
    oldPrice: 32500,
    discount: 13,
    image: "assets/images/products/ac-01.jpg",
    badge: "توفير 40% كهرباء",
    rating: 4.8,
    reviewCount: 97,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: true,
    isDeal: true,
    dealEnds: "2026-10-18T23:59:59"
  },
  {
    id: 10,
    name: "تكييف هيونداي ميني سبليت 2.25 حصان تبريد سريع فائق",
    brand: "Hyundai",
    category: "air-conditioners",
    categoryName: "تكييفات هواء",
    price: 33900,
    oldPrice: 38000,
    discount: 11,
    image: "assets/images/products/ac-02.jpg",
    badge: "قوة تبريد فائقة",
    rating: 4.6,
    reviewCount: 73,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: true,
    isDeal: false
  },
  {
    id: 11,
    name: "ميكروويف باناسونيك ديجيتال سعة 25 لتر مع شواية 900 واط",
    brand: "Panasonic",
    category: "microwaves",
    categoryName: "ميكروويف وشوايات",
    price: 6850,
    oldPrice: 7900,
    discount: 13,
    image: "assets/images/products/microwave-01.jpg",
    badge: "شواية مدمجة",
    rating: 4.7,
    reviewCount: 84,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: true,
    isDeal: false
  },
  {
    id: 12,
    name: "ميكروويف توشيبا الياباني متعدد الوظائف سعة 28 لتر ديجيتال",
    brand: "Toshiba",
    category: "microwaves",
    categoryName: "ميكروويف وشوايات",
    price: 7400,
    oldPrice: 8500,
    discount: 13,
    image: "assets/images/products/microwave-02.jpg",
    badge: "جودة يابانية",
    rating: 4.8,
    reviewCount: 112,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: false,
    isDeal: false
  },
  {
    id: 13,
    name: "بوتاجاز فريش بروفيشنال 5 شعلة ستانلس ستيل مقاس 60×90 أمان كامل",
    brand: "Fresh",
    category: "cookers",
    categoryName: "بوتاجازات وأفران",
    price: 16900,
    oldPrice: 19500,
    discount: 13,
    image: "assets/images/products/cooker-01.jpg",
    badge: "أمان كامل 100%",
    rating: 4.7,
    reviewCount: 138,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: true,
    isDeal: false
  },
  {
    id: 14,
    name: "فرن كهربائي ويرلبول جولد بيلت إن مقاس 60 سم تنظيف ذاتي",
    brand: "Whirlpool",
    category: "cookers",
    categoryName: "بوتاجازات وأفران",
    price: 24500,
    oldPrice: 28000,
    discount: 12,
    image: "assets/images/products/cooker-02.jpg",
    badge: "بيلت إن فاخر",
    rating: 4.8,
    reviewCount: 46,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: true,
    isDeal: false
  },
  {
    id: 15,
    name: "غسالة أطباق بوش سيري 6 ألماني 14 فرد ستانلس موفرة للماء",
    brand: "Bosch",
    category: "dishwashers",
    categoryName: "غسالات أطباق",
    price: 36800,
    oldPrice: 42000,
    discount: 12,
    image: "assets/images/products/dishwasher-01.jpg",
    badge: "تكنولوجيا ألمانية",
    rating: 4.9,
    reviewCount: 91,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: true,
    isDeal: false
  },
  {
    id: 16,
    name: "قلاية هوائية نينجا فودي ماكس مع شواية صحية سعة كبيرة 5.7 لتر",
    brand: "Ninja",
    category: "small-appliances",
    categoryName: "أجهزة منزلية صغيرة",
    price: 11999,
    oldPrice: 14500,
    discount: 17,
    image: "assets/images/products/small-01.jpg",
    badge: "الأكثر طلباً",
    rating: 4.9,
    reviewCount: 204,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: true,
    isDeal: true,
    dealEnds: "2026-10-14T23:59:59"
  },
  {
    id: 17,
    name: "مكنسة تورنيدو سايكلونيك هيبا فلتر قوة شفط 2200 واط",
    brand: "Tornado",
    category: "small-appliances",
    categoryName: "أجهزة منزلية صغيرة",
    price: 4950,
    oldPrice: 5800,
    discount: 15,
    image: "assets/images/products/small-02.jpg",
    badge: "فلتر HEPA طبي",
    rating: 4.6,
    reviewCount: 89,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: false,
    isDeal: false
  },
  {
    id: 18,
    name: "غلاية مياه بوش ستانلس ستيل سريعة الغليان سعة 1.7 لتر",
    brand: "Bosch",
    category: "small-appliances",
    categoryName: "أجهزة منزلية صغيرة",
    price: 2350,
    oldPrice: 2800,
    discount: 16,
    image: "assets/images/products/small-03.jpg",
    badge: "حماية من الغليان الجاف",
    rating: 4.7,
    reviewCount: 163,
    stockStatus: "متوفر بالمخزن",
    inStock: true,
    featured: true,
    isDeal: false
  }
];

const BRANDS_DATA = [
  { name: "Samsung", logoText: "SAMSUNG", arabic: "سامسونج" },
  { name: "LG", logoText: "LG", arabic: "إل جي" },
  { name: "Panasonic", logoText: "Panasonic", arabic: "باناسونيك" },
  { name: "Bosch", logoText: "BOSCH", arabic: "بوش" },
  { name: "Beko", logoText: "beko", arabic: "بيكو" },
  { name: "Fresh", logoText: "FRESH", arabic: "فريش" },
  { name: "Toshiba", logoText: "TOSHIBA", arabic: "توشيبا" },
  { name: "Tornado", logoText: "TORNADO", arabic: "تورنيدو" },
  { name: "Whirlpool", logoText: "Whirlpool", arabic: "ويرلبول" },
  { name: "Ninja", logoText: "NINJA", arabic: "نينجا" }
];
